name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: devbuild

    steps:
      - name: ğŸ§¾ Checkout repository
        uses: actions/checkout@v4

      # Let the action read pnpm version from package.json's "packageManager"
      - name: ğŸ“¦ Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: ğŸ§© Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: ğŸ“š Install dependencies
        run: pnpm install

      - name: ğŸ—ï¸ Build project
        run: pnpm --filter "./apps/dashboard" run build

      - name: ğŸ“¤ Export project
        run: pnpm --filter "./apps/dashboard" run export

      - name: ğŸš€ Deploy to Cloudflare Pages
        working-directory: ./apps/dashboard
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
        run: |
            npx wrangler whoami
            npx wrangler pages deploy ./out \
            --project-name "$CLOUDFLARE_PROJECT_NAME" \
            --branch main